## 异常

### 1.1异常概念

异常，就是不正常的意思。

> 异常：指的是程序在执行过程中，出现的非正常的情况，最终会导致JVM的非正常停止。

在java等面向对象的编程语言中，异常本身是一个类，产生异常就是创建异常对象并抛出一个异常对象，java处理异常的方式就是中断处理。

> 异常指的并不是语法错误，语法错误，编译不通过，产生不了字节码文件，根本不能运行。

### 1.2 异常体系

异常机制其实是帮助我们找到程序中的问题，异常的根类是`java.lang.Throwable`,其下有两个子类:

- `java.lang.Error`
- `java.lang.Exception` 平常说的异常

![image-20200914233954299](%E5%BC%82%E5%B8%B8%E7%AC%94%E8%AE%B0.assets/image-20200914233954299.png)

**Throwable体系**

- Error：严重错误Error,无法通过处理的错误，只好事先避免，相当于绝症
- Exception：表示异常，错误产生后程序员可以通过代码的方式纠正，使程序继续运行，是必须需要处理的，好比感冒、阑尾炎。

**Throwable中的常用方法**：

- `public void printStackTrace() `：打印异常的详细信息

  包含了异常的类型，异常的原因，还包括异常出现的位置，在开发和调试阶段，都得使用printStackTrace

- `public String getMessage()`：获取发生异常的原因

  提示给用户的时候，就提示错误信息

- `public String toString()`：获取异常的类型和异常描述信息(不用)。

出现异常，不要进场，把异常的简单类名，拷贝到API中去查

---

### 1.3异常分类

```java
/*
	java.lang.Throwable类:是java语言所有错误或异常的超类
		Exception：编译期异常，进行编译(写代码)java程序出现的问题
			RuntimeException：运行期异常，java程序经常出现这个问题
			异常处理掉后，程序可以继续执行
		Error：错误
			必须修改源代码，程序才能继续运行
*/
public static void main(String[] args) {
  // Exception:编译期异常，进行编译(写代码)java程序出现的问题
  // 抛出异常后，后续代码依旧可以继续运行
  SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); // 格式化日期
  try {
    date = sdf.parse("19990909"); // 把字符串格式的日期，解析为Date的日期
  }catch(ParseException e) {
    e.printStackTrace();
  }
  System.out.println(date);
  System.out.println("后续代码");
  // RuntimeException：运行期异常
  int[] arr = (1,2,3);
  try{
    System.out.println(arr[3]);
  }catch(Exception e){
    // 异常的处理逻辑
    System.out.println(e);
  }
  /*
  	Error:错误
  		必须修改代码，不然后续不能执行
  */
  int[] arr = new int[1024*1024*1024];
  System.out.println("后续代码");
}
```

---

### 1.4异常的产生过程解析

```java
/*
	异常的产生过程解析(分析异常是怎么产生的，如何处理异常)
*/
public static void main(String[] args) {
  // 创建int类型数组，并赋值
  int[] arr = {1,2,3};
  int e = getElement(arr,3);
  // ArrayIndexOutOfBoundsException:3 数组越界异常
  /* main方法接受到了这个异常对象，main方法也没有异常的处理逻辑
  	 继续把对象抛出给main方法的调用者JVM处理
  	 JVM接受到了这个异常对象，做了两件事
  	 	1. 把异常对象(内容，原因，位置)以红色的字体打印在控制台
  	 	2. JVM会终止当前正在执行的java程序-->中断处理
  */
  System.out.println(e);
}
/*
	定义一个方法，获取数组制定索引处的元素
	参数
		int[] arr
		int index
  访问数组中的3索引，数组没有3索引，jvm就会检测出异常
  jvm会做两件事情
  	1.Jvm会根据异常产生的原因创建一个异常对象，
  		这个异常对象包含了异常产生的(内容，原因，位置)
  	2.在getElement方法中，没有异常的处理逻辑(try...catch)，
  		那么jvm就会把异常对象抛出给方法的拥有者main方法来处理这个异常。
*/
public static int getElement(int[] arr,int index) {
  int ele = arr[index];
  return ele;
}
```

---

## 第二章 异常的处理

java异常处理的五个关键字:`try、catch、finally、throw`、throws

### 2.1抛出异常throw

在编写程序的时候，我们必须要考虑程序出现问题的情况。比如，在定义方法时，方法需要接受参数，那么，当调用方法使用接受到的参数时，受限需要先对参数数据进行合法的判断，数据若不合法，就应该告诉调用者，传递合法的数据进来，这时候需要使用抛出异常的方式来告诉调用者。

在java中，提过了一个**throw**关键字，它用来抛出一个指定的异常对象，那么抛出一个异常具体如何操作呢。

1. 创建一个异常对象，封装一些提示信息(信息可以自己编写)。

2. 需要将这个机场对象告知给使用者，怎么告知呢？怎么将这个异常对象传递到调用者处呢？通过关键字throw就可以完成，throw异常对象。

   throw**用在方法内**，用来抛出一个异常对象，将这个异常对象传递到调用者出，并结束当前方法的执行。

**使用格式：**

```java
throw new 异常类名(参数);
```

例如：

```java
throw new NullPointerException("要访问的arr数组不存在");
/*
	throw关键字
	作用：
		可以使用throw关键字在指定的方法中抛出指定的异常
	注意
		1.throw关键字必须写在方法的内部
		2.throw关键字后边new的对象必须是Exception或者Exception的子类对象
		3.throw关键字抛出指定的异常对象，我们就必须处理这个异常对象
			throw关键字后边创建的是RuntimeException或者RuntimeException的子类对象
			我们可以不处理，默认交给jbm处理(打印异常对象，终端程序)
			throw关键字后边创建的事编译异常(写代码的时候报错)，我们必须处理这个异常
			要么throws，要么try...catch
*/

/*
	定义一个方法，获取数组指定索引处的元素
	参数：
		int[] arr
		int index
	以后(工作中)我们必须对方法传递过来的参数进行合法性校验
	如果参数不合法，那么我们必须使用抛出异常的方式，告知方法的调用者，传递的参数有问题
*/
public static int fetElement(int[] arr,int index) {
  /*
  	我们可以对传递过来的参数数组，进行合法性判断
  	如果数组arr的值时null
  	那么我们就抛出空指针异常，告诉方法的调用者"传递的数组的值是null"
  	注意:
  		NullPointException是一个运行期异常，我们不用处理，交给jvm处理
  */
  if(arr == null) {
    throw new NullPointerException("传递的数组的值是null");
  }
  /*
  	我们可以对传递过来的参数index进行合法性校验
  	如果index的范围不在数组的索引范围内
  	那么我们就抛出数组索引越界异常，告知方法的使用者"传递的索引超出了数组使用范围"
  */
  if(index<0 || index>arr.length - 1) {
    throw new ArrayIndexOutOfBoundsException("传递的索引超出了数组使用范围");
  }
  return arr[index];
}
```

---

### 2.2 Objects非空判断

还记得我们学习过一个类Objects吗，曾经提到过它由一些静态的实用方法组成，这些方法是null-save(空指针安全的)或null-tolerant(容忍空指针的)，那么在它的源码中，对对象为null的值进行了抛出异常的操作。

- `public static <T> T requireNonNull(T obj)`：查看指定引用对象是不是null

查看源码发现这里对null进行了抛出异常操作:

```java
public static <T> T requireNonNull(T obj) {
  if(obj == null) 
    throw new NullPointerException();
  return obj;
}
```

```java
public static Object method(Object obj) {
  /*
  	if(obj==null) {
  	throw new NullPointerException("传递的对象值是null");
  	}
  */
  // Objects.requireNonNull(obj);
  return Objects.requireNonNull(obj,"传递的对象值是null");
}
```

---

### 2.3声明异常throws

> 之后的代码也不会再执行

**声明异常**：将问题标示出来，报告给调用者，如果方法内通过throw抛出了编译时异常，而没有捕获处理(稍后讲解该方式),那么必须通过throws进行声明，让调用者去处理。

关键字**throws**运用于方法声明之上，用于表示当前方法不处理异常，而是提醒该方法的调用者来处理异常(抛出异常).

**声明异常格式：**

```java
修饰符 返回值类型 方法名(参数) throws 异常类名1,异常类名2...{}
```

声明异常的代码演示

```java
public static void read(String path) throws FillNotFoundException {
  if(!path.equals("a.txt")) {
    // 如果不是a.txt这个文件
    // 我假设，如果不是a.txt认为该文件不存在，是一个错误，也就是异常
    throw new FillNotFoundException("文件不存在");
  }
}
```

```java
/*
	throws关键字：异常处理的第一种方式，交给别人处理
	作用：
		当方法内部抛出异常的时候，我们必须处理这个异常对象
		可以使用throws关键字处理异常对象，会把异常对象声明抛出给方法的调用者处理
		(自己不处理，给别人处理)，最终交给JVM处理-->中断处理
	使用格式：在方法声明的时候使用
	注意
		1.throws关键字必须写在方法声明处
		2.throws关键字后面声明的异常必须是Exception或者其子类
		3.方法内部如果抛出了多个异常对象，那么throws后面也必须声明多个异常
				如果抛出的多个异常有子父类关系，那么直接声明父类异常即可
		4.调用了一个声明抛出异常的方法，我们必须处理声明的异常
				要么继续使用throws声明抛出，交给方法的调用者处理，最终交给JVM
				要么try...catch自己处理异常
*/
public static void main(String[]args) {
  
}
/*
	定义一个方法：对传递的文件路径进行合法性判断
	如果路径不是"c://o.txt"，那么我们就抛出文件找不到异常对象，告知方法调用者
	注意：
		FillNotFoundException是编译异常，抛出了编译异常，就必须处理这个异常
		可以使用throws继续声明抛出FillNotFoundException这个异常对象，让方法调用者处理
*/
public static void readFlie(String filemName) thorws FillNotFOundEXception{
  if(!fileNmae.equals("c://a.txt")) {
    throw new FileNotFoundException("传递的文件路径不是c://a.txt");
  }
  /*
  	如果传递的路径，不是.txt结尾
  	那么我们就抛出IO异常对象，告知方法的调用者，文件的后缀名不对
  */
  if(!fileName.edswith("txt")) {
    throw new IOException("文件后缀名不对");
  }
}
```

---

### 2.4 捕获异常try...catch

> 异常之后的代码可以继续执行

如果异常出现的话，会立刻终止程序，所以我们得处理异常:

1. 该方法不处理，而是声明抛出，由该方法的调用者来处理(throws)
2. 在方法中使用try...catch的语句块来处理异常。

**try...catch**的方式就是捕获异常

- 捕获异常：java中国呢怼异常有针对性的语句进行捕获，可以对出现的异常进行指定方式的处理

捕获异常语法如下

```java
try {
  编写可能会出现的异常的代码
}catch {
  处理异常的代码
    // 记录日志/打印异常信息/继续抛出异常
}
```

```java
/*
	try...catch：异常处理的第二种方式，自己处理异常
	格式：
		try {
			可能出生异常的代码
		}catch(定义一个异常的变量，用来接受try中抛出的异常对象) {
			异常的处理逻辑，出现异常对象之后，怎么处理异常对象
			一般在工作中，会把异常的信息记录到一个日志中
		}
		...
		catch(异常类名 变量名) {
		
		}
	注意：
		1.try中可能会抛出多个异常对象，那么就可以使用多个catch处理异常对象
		2.如果try中产生了异常，就会执行catch，执行完后继续执行后续的代码
			如果try没有产生异常，就不会执行catch的代码
*/
public static void main(String[] args) {
  try{
    readFile("d://a.txt");
  }catch(IOException e) { // try中抛出什么异常，catch就定义什么异常
    //异常的处理逻辑，声明异常对象之后，怎么处理异常对象
    System.out.println("catch - 传递的文本后缀不是.txt");
  }
  System.out.println("后续代码");
}
```

如何获取异常信息:

Throwable类中定义了一些查看方法

- `public String getMessage()`:获取异常的描述信息，原因

- `public String toString()` 获取异常的类型和异常描述信息(不用)

- `public void printStackTrace()`:打印异常的跟踪栈信息并输出控制台

  ​	包含了异常的类型，异常的原因、位置，在开发和调试都得用printStackTrace

```java
/*
	Throwable类中定义了一些查看方法
	- public String getMessage():获取异常的描述信息，原因
	- public String toString():获取异常的类型和异常描述信息(不用)
	- public void printStackTrace():打印异常的跟踪栈信息并输出控制台
*/
try{
  
}catch (IOException e) {
  System.out.println(e.getMessage()); // throw 的异常对象的字符串S
  System.out.println(e.toString());// java.io.IOExpception + S 
  System.out.println(e.printStackTrace());// 还包括了在第几行出错
}
```

在开发中也可以在catch将编译期异常转换成运行期异常处理

---

### 。24 finally代码块

**finally**：有一些特定的代码无论异常是否发生，都需要执行，因为异常会引发程序跳转，导致有些语句执行不到。而finally就是解决这个问题的，在finally代码块中存放的代码都是一定会被执行的。

什么时候的代码都必须最终执行？

当我们在rey语句块中打开了一些物力资源(磁盘文件/网络连接/数据库连接等)，我们都得在使用完之后，最终关闭打开的资源。

finally的语法:

rey...catch...finally:自身需要处理异常，最终还得关闭资源。

> 注意：finally不能单独使用
>
> ​			 finally一般用于资源释放，无论程序是否出现异常，最后都要释放资源(IO)

finally代码参考如下：

```java
public static void main(String[] args) {
  try {
    
  }catch{
    
  }finally{
    System.out.println("资源释放");
  }
}
```

---

### 2.5 异常注意事项

多个异常使用捕获又该如何处理呢？

1. 多个异常分别处理
2. 多个异常一次捕获，多次处理
3. 多个异常一次捕获，一次处理

一般我们是使用一次捕获多次处理方式，格式如下:

```java
try {
}catch{
}catch{
}
```

> 注意：这种异常处理方式，要求多个catch中的异常不能相同，并且若catch的多个异常之间有子父类异常的关系，那么子类异常要求在上面的catch处理，父类异常在下面的catch处理。

- 运行时异常被抛出可以不处理，即不捕获也不声明抛出。
- 如果父类抛出了多个异常，子类覆盖父类方法时，只能抛出相同的异常或者它的子集。
- 父类方法没有抛出异常，子类覆盖父类该方法时也不可抛出异常。此时子类产生该异常，只能捕获处理，不能声明抛出。
- 在try/catch后可以追加finally代码块，其中代码一定会被执行，用于资源回收。
- 如果finallu有return语句，永远返回finally中的结果，避免该情况发生。

```java
	public static void main(String[] args) {
    // 1.多个异常分别处理
    try{
    }catch{
    }
    try{
    }catch{
    }
    // 2.多个异常一次捕获，多次处理 最常用
    /*
    	catch里边定义的异常变量，如果有子父类关系，那么子类的异常变量必须写在上边，
    	否则就会报错。
    	如果try出现了异常对象，会把异常对象抛给catch处理，
    	抛出的异常对象会从上到下依次赋值给catch定义的异常变量
    	Index异常从e1开始，e1可以声明，e2就没有被使用
    	Array异常也从e1开始，e1也可以声明，e2也没有被使用
    */
    try{
    }catch(IndexOutOfBoundException e1){ // 父类
    }catch(ArrayIndexOutOfBoundsException e2){ // 子类
    }
    // 3.多个异常一次捕获，一次处理
    try{
    }catch(IndexOutOfBoundsException e){ // 就是定义一个能包括所有的父类
    }
  }
```

---

## 第三章 自定义异常类

### 3.1 概述

**为什么需要自定义异常类：**

我们输了java中不同的异常类，分别表示着某一种具体的异常情况，那么在开发中总是有些异常情况时SUN没有定义好的，此时我们根据自己业务的异常情况来定义异常类，例如年龄负数问题，考试成绩负数问题等等。

**什么是自定义异常类：**

在开发中根据自己业务的异常情况来定义异常类

自定义一个业务逻辑异常RegisterException，一个注册异常类

**异常类如何定义：**

1. 自定义一个编译期异常：自定义类 并继承于`java.lang.Exception`
2. 自定义一个运行时期的异常类:自定义类 并继承于:`java.lang.RuntimeException`

### 3.2自定义异常的练习

要求：我们模拟注册操作，如果用户名已存在，则抛出异常并提示：亲，该用户名已经被注册。

受限定义一个登录异常类RegisterException：

```java
/*
	格式：
		public class XXXException extends Exception / RuntimeException{
			添加一个空参数的构造方法
			添加一个带异常信息的构造方法
		}
	注意：
		1.自定义异常类一般都是以Exception结尾，说明该类是一个异常类
		2.自定义异常类，必须要继承Exception或者RuntimeException
			继承Exception：那么自定义的异常类就是一个编译期异常，如果方法内部抛出了
										编译期异常，就必须处理，要么throws要么try/catch
			继承RuntimeException：那么自定义的异常类就是一个运行期异常，无需处理
*/
public class RegisterException extends Exception {
  // 添加一个空参数的构造方法
  public RegisterException() {
    super();
  }
  /*
  	添加一个带异常信息的构造方法
  	查看源码发现，所以的异常类都会有一个带异常信息的构造方法，
  	方法内部会调用父类信息的构造方法，让父类来处理这个异常信息
  */
  public RegisterException(String message) {
    super(message);
  }
}
```

